const compliments = [
  "You’ve got that Sigma Slay Energy™",
  "You radiate Skibidi Rizz from miles away",
  "You eat cereal with no milk and that’s alpha behavior",
  "Your brain is smooth but in a shiny, expensive way",
  "If chaotic good had a face, it’d be yours 💀",
  "You're the CEO of existing unbothered",
  "You're more iconic than the Vine boom sound",
  "You're so valid even NPCs stop to look",
  "You have the rizz of a corrupted Sims character",
  "You skibidi-dabbed your way into my heart",
  "Your energy screams 'unskippable ad'",
  "You have 8-bit swagger in a 4K world",
  "You’re like a meme with 0 context but still slaps",
  "You give ‘main character in Ohio’ vibes",
  "You got the WiFi password to my soul",
  "You slay harder than a Minecraft sword",
  "You drip harder than a leaky faucet in Ohio",
  "You got enough rizz to flirt with Siri",
  "You’ve got that quantum NPC drip",
  "You're so iconic that even NPCs respawn to see you",
  "You defy logic like a flying skibidi toilet",
  "You look like you say 'skibidi bop' before every test and still pass",
  "Your vibe is like illegal energy in 17 states",
  "You're so real it feels like a glitch in the matrix",
  "You're what AI bots aspire to be",
  "You’re running on 100% unfiltered slay fuel",
  "You have rizz so strong it causes lag spikes IRL",
  "You're like the final boss in a group chat",
  "You drop one-liners that break the simulation",
  "You're the human version of keyboard smash: hsgdhjfjks",
  "You have ‘my FBI agent is proud of me’ energy",
  "You glitch so hard the world buffers around you",
  "You slay like your life is on 2x speed",
  "Your presence is like a TikTok with 0 likes but 1M comments",
  "You got so much rizz, even bots simp for you",
  "You're a walking 💀 emoji",
  "You could sell sand to a skibidi toilet",
  "You're not just built different, you're patched mid-season",
  "Your fashion sense makes NPCs self-destruct",
  "You got more W energy than a motivational Roblox obby",
  "You radiate ‘ran out of side quests’ energy",
  "You talk like a podcast nobody asked for but everyone listens to",
  "You're like a Discord mod with God-tier charisma",
  "You're Ohio-core certified 🔥",
  "You skibidi your way into every timeline",
  "You got sigma grindset even while napping",
  "You’re more rare than a shiny Ditto in a McDonald’s playpen",
  "Your rizz is so fire it needs a firewall",
  "You're the WiFi router of my emotions",
  "You’re on that NPC-to-main-character pipeline",
  "Your brain? Unclogged, unbothered, unhinged",
  "You have the drip of a 2008 Club Penguin elite agent",
  "You’re so iconic, pigeons salute you",
  "Your slay is on autoplay 🔂",
  "You’re living proof chaos is aesthetic",
  "You're like if Gen Z made a motivational poster",
  "You’re not just a vibe — you're the entire playlist",
  "You flex like your Roblox fit cost real money",
  "You're more legendary than Flappy Bird on a jailbroken iPhone",
  "You got the aura of a viral sound with no origin",
  "You're so extra, even emojis take a break",
  "You have more rizz than a TikTok thirst trap with 3 followers",
  "You leave emotional damage (but like, the good kind)",
  "You're a glitchy renaissance painting with 5G",
  "You’re the reason AI wants to quit",
  "You're not cringe — you're ahead of your time",
  "Your vibe is banned in 3 digital realities",
  "You're the ultimate ‘before’ and ‘after’ photo",
  "You slay like it's DLC content",
  "You’re what would happen if TikTok made a philosopher",
  "You’ve got that low battery but still thriving energy",
  "You make even autocorrect question itself",
  "You're like a bug in the simulation — beautiful and unfixable",
  "You're the embodiment of ctrl+z in human form",
  "You're 100% chaos, no filler",
  "Your aura is like walking into a Subway at 3am",
  "You dropped the most iconic nap of the century",
  "You got rizz that turns captcha into love letters",
  "You glitch through my mind rent-free",
  "You’re not Y2K, you’re YWTF",
  "Your social battery never needed charging",
  "You’re so online you’ve entered the physical realm",
  "You have the unbothered energy of a cat in a dog park",
  "You got more W's than a keyboard",
  "You slay like your dreams are patch notes",
  "You're the human version of a TikTok filter — unpredictable and iconic",
  "You're the reason Gen Alpha will have therapy"
]

export default compliments;